version: '3'
networks:
  immo.net:
    driver: bridge

services:
  ## services API PHP ##
  immo-api-php : 
    image: 'canals/php:8.2'
    env_file : ./.env
    ports:
      - '8080:80'
    volumes:
      - ../public:/var/www/html
      - ..:/var/www
    working_dir: /var/www/
    networks:
      - immo.net
    depends_on:
      - db

  ## MySQL service ##
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: password
    networks:
      - immo.net

  ## Adminer service ##
  adminer:
    image: adminer
    ports:
      - '8081:8080'
    networks:
      - immo.net

volumes:
  db_data: